require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OProductsController do

  def mock_o_product(stubs={})
    @mock_o_product ||= mock_model(OProduct, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all o_products as @o_products" do
      OProduct.stub(:all) { [mock_o_product] }
      get :index
      assigns(:o_products).should eq([mock_o_product])
    end
  end

  describe "GET show" do
    it "assigns the requested o_product as @o_product" do
      OProduct.stub(:find).with("37") { mock_o_product }
      get :show, :id => "37"
      assigns(:o_product).should be(mock_o_product)
    end
  end

  describe "GET new" do
    it "assigns a new o_product as @o_product" do
      OProduct.stub(:new) { mock_o_product }
      get :new
      assigns(:o_product).should be(mock_o_product)
    end
  end

  describe "GET edit" do
    it "assigns the requested o_product as @o_product" do
      OProduct.stub(:find).with("37") { mock_o_product }
      get :edit, :id => "37"
      assigns(:o_product).should be(mock_o_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created o_product as @o_product" do
        OProduct.stub(:new).with({'these' => 'params'}) { mock_o_product(:save => true) }
        post :create, :o_product => {'these' => 'params'}
        assigns(:o_product).should be(mock_o_product)
      end

      it "redirects to the created o_product" do
        OProduct.stub(:new) { mock_o_product(:save => true) }
        post :create, :o_product => {}
        response.should redirect_to(o_product_url(mock_o_product))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved o_product as @o_product" do
        OProduct.stub(:new).with({'these' => 'params'}) { mock_o_product(:save => false) }
        post :create, :o_product => {'these' => 'params'}
        assigns(:o_product).should be(mock_o_product)
      end

      it "re-renders the 'new' template" do
        OProduct.stub(:new) { mock_o_product(:save => false) }
        post :create, :o_product => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested o_product" do
        OProduct.stub(:find).with("37") { mock_o_product }
        mock_o_product.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :o_product => {'these' => 'params'}
      end

      it "assigns the requested o_product as @o_product" do
        OProduct.stub(:find) { mock_o_product(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:o_product).should be(mock_o_product)
      end

      it "redirects to the o_product" do
        OProduct.stub(:find) { mock_o_product(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(o_product_url(mock_o_product))
      end
    end

    describe "with invalid params" do
      it "assigns the o_product as @o_product" do
        OProduct.stub(:find) { mock_o_product(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:o_product).should be(mock_o_product)
      end

      it "re-renders the 'edit' template" do
        OProduct.stub(:find) { mock_o_product(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested o_product" do
      OProduct.stub(:find).with("37") { mock_o_product }
      mock_o_product.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the o_products list" do
      OProduct.stub(:find) { mock_o_product }
      delete :destroy, :id => "1"
      response.should redirect_to(o_products_url)
    end
  end

end
